### ISSUE TITLE
Create Model and Services file for /api/v2/pokemon

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/PokeDex#5]
In order to use any API in our Dart code, we have to deserialize the API response in JSON to the so called PODO model.

For reference check out my video on "Working with API in Flutter" : https://youtu.be/ILK1FgrbPbw

Check out the API response: https://pokeapi.co/api/v2/pokemon

We have to create a PODO model to store this API response, and later use them in the Homepage of the app.

This issue requires the contributor to perform two tasks :

1. Create a file `pokemon.dart` inside the `lib/services` folder, which will contain code to connect to the API and retrieve the response. You can use the http package.

2. Create a file `pokemon.dart` inside `lib/models` folder, which will contain the PODO model.

Note: If the folders `services` and `models` are not present, go ahead and create them.

**Comment by iamAbhishekkumar** [comment]
I would like to work on this. : )

**Comment by infiniteoverflow** [comment]
I would sugges you to finish the previous issue. Then I will assign this to you.

**Comment by Starkl7** [comment]
@infiniteoverflow May I work on this issue (as part of SWOC) ?

**Comment by infiniteoverflow** [comment]
Hi @Starkl7 , actually @iamAbhishekkumar has already asked to work on this issue. If he is not able to, then you can go ahead.

@iamAbhishekkumar kindly update if you would like to work on this issue.

**Comment by infiniteoverflow** [comment]
@Starkl7 I will create more issues soon so that you can find the one you like to work on.

**Comment by iamAbhishekkumar** [comment]
> Hi @Starkl7 , actually @iamAbhishekkumar has already asked to work on this issue. If he is not able to, then you can go ahead.
> 
> @iamAbhishekkumar kindly update if you would like to work on this issue.

No I haven't started working on this, but I want to work on this issue.

P.S.- I have already fixed the previous assigned issue.
