### ISSUE TITLE
Create the Home Page (App Bar)

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/PokeDex#6]
We will start one by one. In this issue you need to create just the App Bar of the Homepage screen.

If the page is not there, create one on your own.

What all will the app bar have ?

1. Drawer icon will be an image of a Pokeball : https://cdn.dribbble.com/users/956603/screenshots/6348374/pokeball.png?compress=1&resize=400x300

Make sure the background of the image is removed before using it as an asset in the app.

2. Center widget will be an image of the Official Pokemon title : https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/International_Pok%C3%A9mon_logo.svg/1200px-International_Pok%C3%A9mon_logo.svg.png

3. Ending widget will be a search icon.

Something like this:

![Screenshot 2021-12-17 at 6 56 47 PM](https://user-images.githubusercontent.com/40236624/146551444-8690b581-506f-440a-afe2-7aad26692762.png)

**Comment by brainless-coder** [comment]
I want to work on this issue, can you assign me this issue.

**Comment by infiniteoverflow** [comment]
Sure ,go ahead!
